### PR TITLE
Some fixes for haxe C#

### PR DESCRIPTION
**Pull request by kLabz**
Sorry for the whitespaces, you can see the real changes [here](https://github.com/ciscoheat/buddy/pull/70/files?w=1)

This includes two fixes related to C#:
- [haxe `4.0.0`] a warning about the naming of an unused enum variable
- [haxe `4.0.0` but also `3.4.7`] an error resulting in incorrect C# code (because of some issue with Haxe)

```
src/buddy/Should.cs(829,84): error CS1525: Unexpected symbol `<'
src/buddy/Should.cs(829,130): error CS1525: Unexpected symbol `('
src/buddy/Should.cs(971,254): error CS1525: Unexpected symbol `<'
src/buddy/Should.cs(971,254): error CS1525: Unexpected symbol `)', expecting `;' or `}'
src/buddy/Should.cs(971,254): error CS1525: Unexpected symbol `,', expecting `;' or `}'
src/buddy/Should.cs(971,254): error CS1525: Unexpected symbol `,', expecting `;' or `}'
src/buddy/Should.cs(971,254): error CS1525: Unexpected symbol `)', expecting `;' or `}'
src/buddy/Should.cs(977,254): error CS1525: Unexpected symbol `>'
src/buddy/Should.cs(977,254): error CS1525: Unexpected symbol `)', expecting `;' or `}'
src/buddy/Should.cs(977,254): error CS1525: Unexpected symbol `,', expecting `;' or `}'
src/buddy/Should.cs(977,254): error CS1525: Unexpected symbol `,', expecting `;' or `}'
src/buddy/Should.cs(977,254): error CS1525: Unexpected symbol `)', expecting `;' or `}'
src/buddy/Should.cs(1318,28): error CS1525: Unexpected symbol `<'
src/buddy/Should.cs(1318,54): error CS1525: Unexpected symbol `<'
src/buddy/Should.cs(1320,9): error CS1525: Unexpected symbol `ShouldIterable', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
src/buddy/Should.cs(1320,54): error CS1525: Unexpected symbol `empty'
src/buddy/Should.cs(1320,103): error CS1525: Unexpected symbol `)'
src/buddy/Should.cs(1324,9): error CS1525: Unexpected symbol `ShouldIterable', expecting `class', `delegate', `enum', `interface', `partial', or `struct'
Compilation failed: 18 error(s), 0 warnings
Compilation error
Native compilation failed
```

### CODE REVIEW

**Comment by kLabz** [comment]
Err, still 3 errors:

Flash (both haxe versions):
```
> eval wget -nv -O flash_player_sa_linux.tar.gz https://fpdownload.macromedia.com/pub/flashplayer/updaters/28/flash_player_sa_linux_debug.x86_64.tar.gz
https://fpdownload.macromedia.com/pub/flashplayer/updaters/28/flash_player_sa_linux_debug.x86_64.tar.gz:
2018-06-14 05:55:22 ERROR 404: Not Found.
```

Java (both haxe versions):
```
> haxe -java bin/java -lib travix -lib buddy tests.hxml
haxelib run hxjava hxjava_build.txt --haxe-version 3400 --feature-level 1
javac "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
src/tink/core/_Promise/Promise_Impl_.java:245: error: generic array creation
		tink.core._Future.FutureObject<tink.core.Outcome>[] p = ( (tink.core._Future.FutureObject<tink.core.Outcome>[]) (new tink.core._Future.FutureObject<tink.core.Outcome>[] {null}) );
		                                                                                                                 ^
Note: src/haxe/root/Date.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
Compilation error
Native compilation failed
/home/travis/haxe/lib/tink_core/1,17,0/src/tink/core/Future.hx:64: characters 52-53 : Warning : Type merge.A is being cast to the unrelated type tink.core.Future.T
Error: Build failed
```

All targets, Haxe 4.0.0:
```
Using trace() calls
should reroute the trace output to the reporter (FAILED)
```

Working on this last one.

**Comment by kLabz** [comment]
Created a PR in `tink_core` for the java issue: https://github.com/haxetink/tink_core/pull/85

**Comment by ciscoheat** [comment]
Thank you very much! This issue was on the table but I didn't have any time to look at it yet. So this can be merged now, since the rest of the problem is in tink_core?

**Comment by kLabz** [comment]
Yep, if you can update the flash url.
Additionnally making travis use `tink_core` version `1.16.1` should make all tests pass.

I also opened an issue in Haxe with a minimal repro example about the C# issue, even though we do not need it anymore here (https://github.com/HaxeFoundation/haxe/issues/7200)

**Pull request merged**
